### PR TITLE
Allow libvosk.dll to get loaded on Windows

### PR DESCRIPTION
**Pull request by peterkronenberg**

### CODE REVIEW

**Comment by nshmyrev** [comment]
Sorry, Peter, you removed LibVosk.class, it is critical for android.

**Comment by peterkronenberg** [comment]
It's not removed.  I had a merge conflict, so I had to do a 2nd commit, but it's there

**Comment by nshmyrev** [comment]
I look on "Files Changed" tab and see there is no LibVosk.class argument anymore.

**Comment by peterkronenberg** [comment]
Oh that.  Now I see. I had done my change before the merge, so I didn't see it originally.  Let me make sure it continues to work with that

**Comment by nshmyrev** [comment]
Thank you!

**Comment by peterkronenberg** [comment]
Are the jars on Maven automatically re-built?

**Comment by nshmyrev** [comment]
No, but I republished them right now, you can try to update.

**Pull request merged**
