### PR TITLE
Build and publish with Jitpack

### LINKED ISSUE #558: Add jitpack build
So we can distribute things for F-droid, see

https://forum.f-droid.org/t/google-voice-foss-replica/13629/8

### PR DESCRIPTION
**Pull request by Stypox**
This PR fixes the Android build and tries to add support for publishing to JitPack's repo.

The problems in `build-vosk.sh` were:
- Wrong Android architecture prefix being passed to Kaldi. I've now created a `HOST_KALDI` variable and configured it for each architecture
- Kaldi accidentally prepending architecture prefix twice to ar, as and ranlib. I fixed this externally in alphacep's Kaldi repo, see https://github.com/alphacep/kaldi/pull/2. As a temporary workaround until that PR is merged, that repo has been replaced by my fork in the build script.
- The wrong CXX base was passed to Kaldi:  now the architecture is omitted and it's just `clang++`, since the architecture is added by Kaldi's configuration script
- Some NDK referenced binaries were missing. Now the script just creates some symlinks in NDK's `bin/` folder and everything builds well (I even tested building Dicio with the generated aar and it worked, so the symlinks are ok). If you have a better solution for this please tell me; I already tried symlinking in another directory and adding it to PATH but `cmake` would raise issues about a missing `link` command.

Other problems:
- The `lib/build.gradle` file was passing the sdk folder instead of the ndk one as `ANDROID_NDK_HOME` to `build-vosk.sh`. Fixed (note that you have to specity `ndk.dir` in `local.properties`; this is deprecated but jitpack does it this way).
- `build-vosk.sh` was not invoked before building the aars, leading to empty aars

Other changes:
- I added `set -xe` on top of `build-vosk.sh` so that the script prints all commands being executed and exits whenever any command fails
- Whenever a git repo to clone already existed the `build-vosk.sh` script would quit; now that error is simply ignored and a message is printed out. This has no effect on jitpack builds, but helps when testing.
- `vosk-api` was recloned 4 times inside the build folder, now just `src/` is copied from the repo's root directory
- I added the gradle wrapper, required for jitpack to set the correct gradle version

Still to do:
- [ ] Once https://github.com/alphacep/kaldi/pull/2 is merged, revert to using alphacep's Kaldi repo instead of mine
- [ ] JitPack still fails because OpenBLAS uses GCC, but it is missing since `build-essential` is not installed on JitPack's VM, see [this log](https://jitpack.io/com/github/Stypox/vosk-api/d159de6ded/build.log). There is a PR open since two years adding it, I pinged Jitpack's developers hoping they will merge it: https://github.com/jitpack/dockerfiles/pull/1. I tried to find workarounds, such as using the clang executable included in the NDK (but this leads to missing `stdio.h` header or to `ld` failing after I added some `-I/path/to/includes/that/may/make/sense` to the compiler flags) or installing gcc in a local folder using [GSRC](http://www.gnu.org/software/gsrc/) (but this leads to even more missing packages on JitPack, such as `lzip`), but without success.

Closes #558 @nshmyrev @k3b

### CODE REVIEW

**Comment by nshmyrev** [comment]
Thanks, let me check

**Comment by nshmyrev** [comment]
> still fails because OpenBLAS uses GCC

It should be perfectly possible to build with clang

**Comment by Stypox** [comment]
I think clang is not installed in the VM either, since if I replace gcc by clang I get the same error as if I replaced it by the NDK's clang, i.e. "could not include stdio.h", so I guess the clang used is just the one found under the NDK's build folder

**Comment by nshmyrev** [comment]
>  i.e. "could not include stdio.h"

I believe we need sysroot option for that:

https://stackoverflow.com/questions/52523080/android-ndk-fatal-error-stdio-h-no-such-file-or-directory-include-stdio-h

**Comment by Stypox** [comment]
I followed the instructions from the link you gave, but it turned out we can't use the NDK's build tools to generate executables for the host machine, since that would result in "invalid ELF header". I tried with all four architectures provided by the ndk but none worked. Now I'm trying another way, i.e. to download clang from their releases and trying to use it without installing it. I will update you on the outcome

**Comment by nshmyrev** [comment]
>  i.e. to download clang from their releases and trying to use it without installing it. 

Hold on with this, I'll take a look myself. You certainly don't need anything beside NDK

**Comment by Stypox** [comment]
@nshmyrev the issue is that OpenBLAS needs to compile and execute some C code to get information about the system in which to build (see the getarch makefile target). Since that code needs to be executed on the host machine, it needs to be compiled with a host-compatible compiler

**Comment by Stypox** [comment]
@nshmyrev do you want to try something yourself or shall I keep trying to download a compiler inside the vm?

**Comment by nshmyrev** [comment]
> @nshmyrev do you want to try something yourself or shall I keep trying to download a compiler inside the vm?

I'll try myself, give me this week please

**Comment by nshmyrev** [comment]
I have pushed more or less this changes, thank you! Now it should work with latest ndk. As for jitpack, I'm pushing jars on sonatype today, so this should not be relevant. I don't want to support too many CI systems.

**Comment by nshmyrev** [comment]
Done https://s01.oss.sonatype.org/content/repositories/releases/com/alphacephei/vosk-android/0.3.32/, not sure if it is public already or not

**Comment by Stypox** [comment]
For your interest, now Jitpack added `build-essential` to their build machines: https://github.com/jitpack/dockerfiles/pull/1

**Pull request closed without merging**
