### PR TITLE
Kaldi remove lm target because rnnlm has lm

### PR DESCRIPTION
**Pull request by msqr1**
Target rnnlm already includes lm, so no need to specify lm anymore

### CODE REVIEW

**Comment by msqr1** [comment]
@nshmyrev

**Comment by nshmyrev** [comment]
Not sure what is the point? It should not affect build in any way

**Comment by msqr1** [comment]
Make stuff shorter, I guess

**Comment by nshmyrev** [comment]
Ok, thanks!

**Pull request merged**
