### PR TITLE
Add Kotlin Multiplatform

### PR DESCRIPTION
**Pull request by Doomsdayrs**
By using Kotlin multiplatform, we can deprecate duplicated code that is `android` and `java`.

This can also be setup for Kotlin/Native, Kotlin/IOS and Kotlin/JS in the future.

### CODE REVIEW

**Comment by Doomsdayrs** [comment]
Should this be a separate project with its own release schedule?

**Comment by Doomsdayrs** [comment]
This has been ready, I just need someone to review what I made.

**Comment by nshmyrev** [comment]
Very nice, thank you! Let us know if any help is needed please

**Comment by nshmyrev** [comment]
Should we make an announcement on this?

**Comment by Doomsdayrs** [comment]
> Should we make an announcement on this?

Woah woah woah Woah that happened as soon as I made the byteflow waveform commit.

Thanks goodness this happened at the right times else we would have had some issues with prs.

**Comment by Doomsdayrs** [comment]
We should not announce anything before the entire stack is possible.

Small roadmap.
- [ ] Publish to maven central
- [ ] Update dependents
  - [ ] [demo](https://github.com/alphacep/vosk-android-demo)
  - [ ] [android-service](https://github.com/alphacep/vosk-android-service)
- [ ] Update documentation

**Comment by Doomsdayrs** [comment]
I will make a new issue for tracking our progress for this.

**Pull request merged**
