### PR TITLE
Types for typescript projects, and jsDoc

### PR DESCRIPTION
**Pull request by Sharcoux**
I allowed myself to provide some more details on your awesome API. Please don't merge without reading it, and once you had had some fun, please help me fill the gaps. ;)

### CODE REVIEW

**Comment by nshmyrev** [comment]
Thank you François, looks promising.

Between, you can find detailed API doc for C code in the header:

https://github.com/alphacep/vosk-api/blob/master/src/vosk_api.h

it provides the details for methods used with proper description. I have no idea though how to integrate it automatically, we need some documentation scripts probably so we can document the APIs for different languages, seems like a problem.

**Comment by Sharcoux** [comment]
Perfect ! I'm on it.

**Comment by Sharcoux** [comment]
Here are some questions I have to ask to complete the documentation:

  * **conf**: Is this a rate between 0 and 1?
  * **start** & **end**: What is the unit of the value returned? ms? seconds?
  * **acceptWaveform**: What type of data are being accepted exactly? Stream? ArrayBuffer? UInt16Array?
  * **vosk_spk_model_ptr**: The value is being declared but never being used. Should we remove?

I also made a proposition for #462 that will be transparent for current users.

> we need some documentation scripts probably so we can document the APIs for different languages

We might work on a script later. For now, I think that manually adding the details might be enough

**Comment by nshmyrev** [comment]
> conf: Is this a rate between 0 and 1?

yes, it is float between 0 and 1

> start & end: What is the unit of the value returned? ms? seconds?

it is float in seconds

> acceptWaveform: What type of data are being accepted exactly? Stream? ArrayBuffer? UInt16Array?

I believe it must be a Buffer

> vosk_spk_model_ptr: The value is being declared but never being used. Should we remove?

You'd better add wrappers for vosk_recognizer_new_spk and vosk_recognizer_new_grm

**Comment by Sharcoux** [comment]
image

Much better :)

> You'd better add wrappers for vosk_recognizer_new_spk and vosk_recognizer_new_grm

On it!

**Comment by Sharcoux** [comment]
@nshmyrev Are Speaker Models sources the same as Models: https://alphacephei.com/vosk/models

And if so, why would you need both a Model and a SpeakerModel when calling `vosk_recognizer_new_spk`? If being built from the same file, SpeakerModel should probably just extend Model.

When using `vosk_recognizer_new_spk` instead of `vosk_recognizer_new`, will I receive different results? What is the shape of those results?

Is it not possible to use both `spk` and `grm`? I would imagine that the correct signature would be something like:

```typescript
  constructor(model: Model | SpeakerModel, sampleRate: number, grammar?: string[]);
```

**Comment by Sharcoux** [comment]
@nshmyrev If you can answer me on the previous question, I think that the fix might be over.

**Comment by mmende** [comment]
@Sharcoux SpeakerModel is not the same as Model and is only used to calculate speaker vectors as far as I know. Furthermore, the only exposed constructor in the nodejs library right now is `Recognizer(model: Model, sample_rate: number)`. The result string returned by `recognizer.result()` and `recognizer.finalResult()` contain a json string in this form:

```ts
interface WordInfo {
  conf: number
  start: number
  end: number
  word: string
}

interface Result {
  result: WordInfo[]
  text: string
}
```

...while `recognizer.partialResult()` returns a json string in this form `{ partial: string }`.

I am currently working on exposing the rest of the vosk-api completely in typescript and hope, that together with your jsDoc enhancements, we can make the experience for js developers even better.

@nshmyrev is switching from js to typescript an option for you? The only downside I see is, that a typescript implementation would increase the boilerplate when working on the typescript api itself.

**Comment by Sharcoux** [comment]
@mmende Thanks a lot for your answer, but I think that you missed most of my points.

 > SpeakerModel is not the same as Model and is only used to calculate speaker vectors as far as I know.

The question was about the source files for Model and SpeakerModel. Are they the same files? And if not, where can I find those files for SpeakerModel?

> The result string returned by recognizer.result() and recognizer.finalResult() contain a json string in this form:

This is the result when using `vosk_recognizer_new` and it is already documented in this PR. The question is for when using `vosk_recognizer_new_spk`. How are the speaker vectors returned in this last case?

> I am currently working on exposing the rest of the vosk-api completely in typescript and hope, that together with your jsDoc enhancements, we can make the experience for js developers even better.

The jsDoc is understood by every modern IDE I can think of. I don't really see the benefits of switching to typescript. The current approach makes the lib fully compatible with both js and typescript projects.

**Comment by mmende** [comment]
Ah ok sorry. I should have taken a closer look at your PRs before.

To use SpeakerModel you have to call `vosk_recognizer_new_spk` with a `VoskModel` instance as first argument (which is responsible for speech to text) and a `VoskSpkModel` instance as second argument (which is responsible for speaker identification) and the sampleRate as third argument. Using speaker identification + grammar seems not to be possible right now as the api has no constructor that accepts a SpeakerModel + grammar. A pretrained SpeakerModel can be found on the [models page](https://alphacephei.com/vosk/models) under [Speaker identification model](https://alphacephei.com/vosk/models/vosk-model-spk-0.4.zip).

When using the SpeakerModel constructor the `Result` type mentioned earlier looks like this:

```ts
interface Result {
  result: WordInfo[]
  text: string
  spk: number[]
  spk_frames: number
}
```


To the advantages of using typescript directly:

Using typescript does not only help api users but it also uncovers implementation errors due to static code analysis for example. This is how I found some bugs already at least. The transpiled code that ends up in the published package can also be used without using typescript at all and is therefore also fully compatible with both js and typescript. And in the end I guess it has also to do with personal preference. 

Kind regards

**Comment by Sharcoux** [comment]
Actually, you're right, I forgot something important: if you add `// @ts-ignore` to the start of the file, you get ts checks even in js file.

Adding it revealed the errors you are probably mentioning. I fixed there too.

**Comment by Sharcoux** [comment]
Ok, @mmende  @nshmyrev , the PR is ready I think. Can one of you just give me a good description for `spk` and `spkFrames` in the results? I don't exactly understand what it is.

Thanks @mmende for providing me the last details.

**Comment by nshmyrev** [comment]
> the PR is ready I think. Can one of you just give me a good description for spk and spkFrames in the results? I don't exactly understand what it is.

Can you please resolve the conflict?

> Can one of you just give me a good description for spk and spkFrames in the results?

spk is a floating vector representing speaker identity. It is usually about 128 numbers which uniquely represent speaker voice.

spkFrames is number of frames used to extract speaker vector. The more frames you have the more reliable is speaker vector.

**Comment by Sharcoux** [comment]
Ok, conflicts resolved and params definition updated.

So, depending on if you provide a SpeakerModel or not,  the Result type will change automatically :+1: 

The Intellisense doesn't handle JSDoc multiple signatures syntax, so I thought it was better to keep only one signature.

With SpeakerModel:

image

Without SpeakerModel:

image

**Comment by nshmyrev** [comment]
Looks ok for me. @mmende is it ok for you?

I would better have named parameters for constructor though, I find this grammarOrModel pretty ugly.

**Comment by Sharcoux** [comment]
@nshmyrev I agree, but I don't see exactly how I could achieve that. I could call it `option` if you prefer, and `option` would be string[] or SpeakerModel. But there is no way, I think, to have 2 constructors with different parameters' names.

**Comment by nshmyrev** [comment]
> But there is no way, I think, to have 2 constructors with different parameters' names

You can have one constructor but with named  arguments:

     const num = myCustomParseInt({ item: '100', radix: 10 });

in the future we will have more options and parameters to constructor so I believe we'll keep API extensible this way.

**Comment by Sharcoux** [comment]
We could do this but:

1) this would introduce a breaking change
2) I'm not sure that we can inform the user that grammar and SpeakerModel cannot both be specified at the same time, the same way it is right now.

I think that for now, the best would be to rename the field `option` and we can extend its type according to further evolutions. Don't you think?

**Comment by mmende** [comment]
Looks good for me. But concerning the constructor, an option object would be the best idea in my opinion as well (especially when there are more options to come). Furthermore, the constructor could be overloaded to also support both, the current as well as the new signature:

```ts
constructor(model: Model, sampleRate: number)
constructor(options: Options)
```

The type of signature can then simply be checked like this:

```js
constructor(options, maybeSampleRate) {
  const model = options instanceof Model ? options : options.model;
  const sampleRate = typeof maybeSampleRate === 'number' ? maybeSampleRate : options.sampleRate;
  let spkModel = null;
  let grammar = null;
  if (!(options instanceof Model)) {
    const {
      sampleRate: optSampleRate,
      grammar: optGrammar,
      spkModel: optSpkModel
    } = options
    if (Array.isArray(optGrammar)) {
      grammar = JSON.stringify(optGrammar);
    }
    if (optSpkModel) {
      spkModel = optSpkModel;
    }
  }
  if (spkModel && grammar) {
    throw new Error('spkModel and grammar cannot be used concurrently yet');
    // This could of course also be a console.warn
    // but it seems to be pretty unpopular to produce uncontrollable console statements these days
  }
  if (grammar) {
    this.handle = libvosk.vosk_recognizer_new_grm(model.handle, sampleRate, grammar);
    return;
  }
  if (spkModel) {
    this.handle = libvosk.vosk_recognizer_new_spk(model.handle, spkModel.handle, sampleRate);
    return;
  }
  this.handle = libvosk.vosk_recognizer_new(model.handle, sampleRate);
}
```

This way the api would not introduce breaking changes but would also be future proof.

PS: I didn't want to annoy you with the typescript question anymore ;-) ... but I'd still be more than happy to turn the api's codebase into typescript once the full vosk-api is exposed and documented with these PRs.

**Comment by nshmyrev** [comment]
Hello

We do not care about backward compatibility right now. I prefer the constructor with named args.

**Comment by mmende** [comment]
In this case the nicest solution would probably be:

```js
constructor({ model, sampleRate, grammar, spkModel }) {
  if (spkModel && grammar) {
    throw new Error('spkModel and grammar cannot be used concurrently yet');
    // This could of course also be a console.warn
    // but it seems to be pretty unpopular to produce uncontrollable console statements these days
  }
  if (grammar) {
    this.handle = libvosk.vosk_recognizer_new_grm(model.handle, sampleRate, JSON.stringify(grammar));
    return;
  }
  if (spkModel) {
    this.handle = libvosk.vosk_recognizer_new_spk(model.handle, spkModel.handle, sampleRate);
    return;
  }
  this.handle = libvosk.vosk_recognizer_new(model.handle, sampleRate);
}
```

If backward compatibility is not a thing anyway, it maybe also a good idea to directly call the parsed result methods `result()`, `partialResult()` and `finalResult()` instead of adding the `Obj` suffix...

**Comment by Sharcoux** [comment]
@mmende Overloading the constructor this way is a typescript feature. JSDoc has it's own syntax for that, but it's not recognized by VSCode intellisense. That's  why I'm not convinced that it's such a good idea.

If breaking change is not an issue, I also recommend Removing the Object suffix and discarding the original functions that return JSON strings. I'll do that right now.

**Comment by mmende** [comment]
I know...I only used it to describe the constructor signatures

**Comment by Sharcoux** [comment]
Actually, I'm still a bit annoyed by changing the parameters into an object. With such a change, the following will raise no error and it will give unpredictable results:

```js
    rec = new vosk.Recognizer({
      model,
      sampleRate: sampleRate || 16000.0,
      grammar: [],
      speakerModel: new vosk.SpeakerModel(""),
    });
```

The user will receive results that are not within the grammar list and won't understand why. And you can be 100% sure that you will see them raising errors here in the issue section, wasting the time of everyone.

Or maybe there is a way to type this correctly, but I didn't find it.

**Comment by mmende** [comment]
You could raise a runtime error when grammar and speakerModel are being used together like this:

```js
if (speakerModel && grammar) {
  throw new Error('speakerModel and grammar cannot be used together yet');
}
```

**Comment by Sharcoux** [comment]
Ok, I found a solution. The only down side is that the error raised in the IDE when setting both grammar and speakerModel is not that clear.

I have 2 last points to raise:

1) Are we 100% sure that `acceptWaveform` param is of type `Buffer`?
2) If the only way to create a `Model` is through `new Model()` and the only use case of this Model is in the `Recognizer` object, wouldn't it make much more sense to just pass the `path` to the model to the Recognizer, instead of asking the user to manually instantiate those? Same goes for SpeakerModel.

About 2), I suggest that we replace model by `modelPath: string` and speakerModel by `speakerModelPath: string`. This way, the user won't need to worry about the instantiation of those.

**Comment by mmende** [comment]
To:

1. Yes, I've tested that successfully
2. I think it's a good idea to stay close to the original API in this respect in case the Model or SpeakerModel classes will be changed or extended at some point

**Comment by Sharcoux** [comment]
But about 2), making the user instantiate the Model increase the risk of creating breaking changes when the Model will evolve or when the structure management will change. By simplifying this and making the user need to only provide the details to the Recognizer object, we make it simpler for them to understand the API, and safer against breaking changes.

**Comment by mmende** [comment]
Why should this increase the risk of creating breaking changes? If the constructor would change, it would also create breaking changes when you only provide the modelPath in the Recognizer constructor... Also the API is really simple if you ask me. I think if there are good examples on how to use the API, it should be really easy to get started with it.

**Comment by mmende** [comment]
Besides that, this allows sharing Models across Recognizers (without having to reload them every time you create a Recognizer).

**Comment by Sharcoux** [comment]
About the breaking change, it's just that, for instance, changing Model to a new structure: ComplexModel that would do more stuff will create a breaking change whereas the inner data structure should IMO be transparent to the user.

But your last point is very valid.

**Comment by Sharcoux** [comment]
@nshmyrev I think that we're good here. You can give a last review and merge I think. Do you agree @mmende ?

**Comment by Sharcoux** [comment]
Wait a minute. I missed an issue

**Comment by Sharcoux** [comment]
Ok, fixed.

**Comment by nshmyrev** [comment]
Amazing, thank you!

**Comment by Sharcoux** [comment]
Do you know when you intend to release?

**Comment by nshmyrev** [comment]
Just published 0.3.24, thank you! Changed a bit the result vs resultObject and fixed demo. Now looks great! Thank you guys.

**Comment by Sharcoux** [comment]
Argh!!! I forgot to remove the @deprecated tag on the result functions!!!

**Pull request merged**
