### PR TITLE
Fix: go mod

### PR DESCRIPTION
**Pull request by Ferrany1**
Go build fix with README

### CODE REVIEW

**Comment by Ferrany1** [comment]
https://github.com/alphacep/vosk-api/issues/708

**Comment by nshmyrev** [comment]
Hi. What is the point to change module path? It has to be vosk-api/go as it was before.

**Comment by Ferrany1** [comment]
The problem is that currently its cannot be compiled from import, whole project needs to be git cloned to get access to src dir. Changing path includes src in module so it can be compiled through direct import + release binary

**Comment by nshmyrev** [comment]
You still can compile it as is. Release package includes the header file. You do not need sources, they are useless.

**Comment by Ferrany1** [comment]
You're totally correct, in my latest attempt I've completely missed CGO_CPPFLAGS flag. However README may be edited to help others to build server

**Comment by nshmyrev** [comment]
Yes, if you could just submit README, it would be nice! Without module path change (it is already uploaded to go.com). Thank you.

**Pull request closed without merging**
