### PR TITLE
JSON float value does not depend on current locale (fixes #808)

### LINKED ISSUE #808: JSON formatting broken in locale with comma separator
Hello,
first off, thank you for this piece of software. It runs very well and is easy to use.
It seems though that I ran into a bug (sorry if I'm wrong).
My locale is fr_FR and therefore floating numbers are formatted with a comma (ie 1,3 and not 1.3 as in English).
Now when I set vosk_recognizer_set_max_alternatives to more than one, vosk_recognizer_result and vosk_recognizer_final_result return a json string containing several alternatives with a confidence level for each one expressed as a floating number. It turns out that this number is formatted according to the locale (with a comma) which makes the string unreadable by common json parsers since we get things like : 
  "alternatives" : [{
      "confidence" : 361,788818,
      "text" : ""
    }]

and commas are used by json to separate values. If I save the locale, change it to us_US, execute one of the above functions and change it back to what it was, it works (floating numbers are formatted with a dot).
I suspect we should get the same problem with vosk_recognizer_set_words (I didn't try though).
Thank you.

### PR DESCRIPTION
**Pull request by IvanPinezhaninov**

### CODE REVIEW

**Comment by nshmyrev** [comment]
Thats probably going to be very slow

**Comment by IvanPinezhaninov** [comment]
You are absolutely right! Didn't think about speed. Did some tests and can suggest using snprintf. It's fast enough. Here are the tests and results: [main.zip](https://github.com/alphacep/vosk-api/files/9071825/main.zip)

**Comment by nshmyrev** [comment]
Yes, the approach with simple replace of , an . is probably going to be the best

**Comment by whirvis** [comment]
This implementation is broken. This code:
```cpp
std::string str = std::to_string(Internal.Float);
auto it = str.find(',');
return (std::string::npos != it) ? str.replace(it, it, 1, '.') : str;
```
Will return `1234.8` if the output of `std::to_string(Internal.Float)` is `1234,5678` because the call to `str.replace()` is incorrect. The second argument (count) should be `1`, not `it`. This can be fixed in one of two ways. Either fix the call to `str.replace()`:
```cpp
std::string str = std::to_string(Internal.Float);
auto it = str.find(',');
return (std::string::npos != it) ? str.replace(it, 1, 1, '.') : str;
```
- See the [eighth definition of `std::string::replace`](https://en.cppreference.com/cpp/string/basic_string/replace).

Or use (in my humble opinion) this easier to read implementation:
```cpp
std::string str = std::to_string(Internal.Float);
size_t it = str.find(',');
if (it != std::string::npos) {
    str[it] = '.';
}
return str;
```

Also:
> Thats probably going to be very slow

Even if this is the case, I would rather this function work slowly, than not work at all. This has been an issue for [nearly five years](https://github.com/alphacep/vosk-api/pull/808). The [recommended workaround](https://github.com/alphacep/vosk-api/issues/808#issuecomment-2740891193) is to *parse the entire JSON output to replace the commas with periods in the correct spots*. This is an insane approach that is magnitudes slower than just doing it in the `dump()` function.

**Pull request closed without merging**
